Repository 9oormthon-univ/2024_DANPOONG_TEAM_51_FE, pull requests merged in 2024-11, with the labels that each got.

#2 [Setting] #1 - 프로젝트 초기세팅
  .gitignore
  README.md
  eslint.config.js
  index.html
  package.json
  public/vite.svg
  src/App.tsx
  src/Router.tsx
  src/common/asset/font/Pretendard-Bold.woff2
  src/common/asset/font/Pretendard-Regular.woff2
  src/common/asset/image/react.svg
  src/common/asset/image/tabBar/chat.svg
  src/common/asset/image/tabBar/home.svg
  src/common/asset/image/tabBar/mypage.svg
  src/common/asset/image/tabBar/selectedChat.svg
  src/common/asset/image/tabBar/selectedHome.svg
  src/common/asset/image/tabBar/selectedMypage.svg
  src/common/style/GlobalStyle.ts
  src/common/style/style.d.ts
  src/common/style/theme.ts
  src/main.tsx
  src/page/main/Main.tsx
  src/page/main/chat/Chat.tsx
  src/page/main/component/TabBar.tsx
  src/page/main/home/Home.tsx
  src/page/main/mypage/Mypage.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: 🌱 Feat, 🐸 정

#4 [Feat] #3 - 버튼 컴포넌트 추가
  src/Router.tsx
  src/page/component/button/Button.tsx
  src/page/index/BtnTest.tsx
Labels: 🌱 Feat, 🐯 동건

#6 [Fix] #5 - 패키지 재설치
  package.json
  yarn.lock
Labels: 🎈 Fix, 🐸 정

#9 [Feat] 인덱스 페이지 구현
  public/bg-gradient.png
  src/App.tsx
  src/Router.tsx
  src/common/asset/image/index/icon-kakao.svg
  src/common/asset/image/index/logo-title.png
  src/common/asset/image/index/tooltip-triangle.png
  src/common/style/index/IndexStyle.ts
  src/page/component/button/BtnTest.tsx
  src/page/index/Index.tsx
  src/page/index/SignUp.tsx
Labels: 🌱 Feat, 🦋 Design, 🐯 동건

#12 [Design] #7 - 채팅 레이아웃 구현
  .prettierrc
  package.json
  src/App.tsx
  src/Router.tsx
  src/common/asset/image/chatting/activationSendButton.svg
  src/common/asset/image/chatting/bg-gradient.png
  src/common/asset/image/chatting/calendarIcon.svg
  src/common/asset/image/chatting/fileIcon.svg
  src/common/asset/image/chatting/imageIcon.svg
  src/common/asset/image/chatting/mentoringStartIcon.svg
  src/common/asset/image/chatting/sendButton.svg
  src/common/asset/image/chatting/userProfile.svg
  src/common/asset/image/component/chevron-left.svg
  src/common/asset/image/component/cone_logo.svg
  src/common/style/custom.d.ts
  src/common/style/style.d.ts
  src/common/style/svg.d.ts
  src/common/style/theme.ts
  src/page/component/navi/Navigation.tsx
  src/page/main/chat/chatting/ChattingPage.tsx
  src/page/main/chat/chatting/component/Chatting.tsx
  src/page/main/chat/chatting/component/ChattingMessageInput.tsx
  src/page/main/chat/chatting/component/MentoringStart.tsx
  src/vite-env.d.ts
  src/vite-env.override.d.ts
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: 🌱 Feat, 🦋 Design, 🐸 정

#13 [Feat] #11 - 더 많은 버튼!
  src/Router.tsx
  src/common/asset/image/component/chevron-right.svg
  src/common/asset/image/user-profile-default.svg
  src/common/style/theme.ts
  src/page/component/Badge.tsx
  src/page/component/ComponetsTest.tsx
  src/page/component/Profile.tsx
  src/page/component/button/Button.tsx
  src/page/component/button/ButtonBig.tsx
  src/page/component/button/ButtonSmall.tsx
  src/page/index/Index.tsx
  src/page/index/SignUp.tsx
Labels: 🌱 Feat, ☂️ Chore, 🐯 동건

#15 [Setting] #14 - 서버 연결 초기세팅
  .gitignore
  index.html
  package.json
  public/favicon.svg
  src/page/component/navi/Navigation.tsx
  src/page/index/Index.tsx
  src/shared/api/instance.ts
  src/shared/api/login/index.ts
  src/shared/api/login/type.ts
  src/shared/constant/path.ts
  vite-env.d.ts
  vite-env.override.d.ts
  yarn.lock
Labels: ⚙️ Setting, 🐸 정

#18 [Design] #10 - 음성통화 레이아웃 구현
  package.json
  src/App.tsx
  src/Router.tsx
  src/common/asset/image/voicecall/calendar.svg
  src/common/asset/image/voicecall/loader.lottie
  src/common/asset/image/voicecall/mic-muted.svg
  src/common/asset/image/voicecall/mic.svg
  src/common/asset/image/voicecall/phone-down.svg
  src/common/asset/image/voicecall/profile-circles.lottie
  src/common/asset/image/voicecall/speaker-wave.svg
  src/common/style/voicecall/VoiceCallStyle.ts
  src/page/component/Badge.tsx
  src/page/voicecall/VoiceCall.tsx
  src/page/voicecall/component/BtnGroupVoiceCall.tsx
  src/page/voicecall/component/Loader.tsx
  src/page/voicecall/component/ProfileWrapper.tsx
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: 🌱 Feat, 🦋 Design, 🐯 동건

#22 Feat/#20 mypage component
  src/common/style/style.d.ts
  src/common/style/theme.ts
  src/page/component/ComponetsTest.tsx
  src/page/component/ProfileCard.tsx
  src/page/component/button/ButtonBig.tsx
Labels: 🌱 Feat, 🦋 Design, 🐯 동건

#21 [Feat] #16 - 카카오 로그인 구현
  src/Router.tsx
  src/page/index/Index.tsx
  src/page/index/KakaoCallback.tsx
  vite.config.ts
Labels: 🌱 Feat, 🐸 정

#25 [Fix] #24 - ButtonBig 컴포넌트 수정
  src/page/component/ComponetsTest.tsx
  src/page/component/button/ButtonBig.tsx
Labels: 🎈 Fix, 🐯 동건

#27 [Design] #23 - 채팅 페이지 내 전화 버튼 추가
  src/App.tsx
  src/common/asset/image/chatting/CallDescription.svg
  src/common/asset/image/chatting/call-button.svg
  src/page/index/KakaoCallback.tsx
  src/page/index/SignUp.tsx
  src/page/main/chat/chatting/ChattingPage.tsx
  src/page/main/component/TabBar.tsx
  src/shared/api/instance.ts
  src/shared/api/signup/index.ts
  src/shared/api/signup/type.ts
  src/shared/api/user/index.ts
Labels: 🌱 Feat, 🦋 Design, 🐸 정

#28 [Feat] #26 - 멘토링 시간예약 페이지 구현
  package.json
  src/App.tsx
  src/Router.tsx
  src/common/asset/image/component/message-alert.svg
  src/common/asset/image/component/notice.svg
  src/page/component/ComponetsTest.tsx
  src/page/component/Notification.tsx
  src/page/main/chat/book/Book.tsx
  src/page/main/chat/chatting/component/ChattingMessageInput.tsx
  yarn.lock
Labels: 🌱 Feat, 🦋 Design, 🐯 동건

#30 [Feature] #17 - 채팅 기능 구현
  .gitignore
  package.json
  src/common/asset/image/home/banner_mentee.png
  src/common/asset/image/home/banner_mentor.png
  src/common/asset/image/home/mentoring-explain.png
  src/main.tsx
  src/page/component/navi/Navigation.tsx
  src/page/index/SignUp.tsx
  src/page/main/Main.tsx
  src/page/main/chat/chatting/ChattingPage.tsx
  src/page/main/chat/chatting/component/MentoringStart.tsx
  src/page/main/home/Home.tsx
  src/shared/api/chatting/index.ts
  src/shared/api/chatting/type.ts
  src/shared/api/user/index.ts
  src/shared/api/user/type.ts
  vite.config.ts
  yarn.lock
Labels: 🌱 Feat, 🐸 정

#31 [Feat] #19 - 음성통화 구현
  package.json
  src/common/asset/image/voicecall/calendar.svg
  src/common/asset/image/voicecall/phone-down-white.svg
  src/common/asset/image/voicecall/phone-up-white.svg
  src/common/style/voicecall/VoiceCallStyle.ts
  src/page/component/ComponetsTest.tsx
  src/page/main/chat/chatting/ChattingPage.tsx
  src/page/voicecall/VoiceCall.tsx
  src/page/voicecall/component/BtnGroupCallee.tsx
  yarn.lock
Labels: 🌱 Feat, 🐯 동건
